version: '3.8'
services:
  db:
    image: postgres:14.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE:-house_app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  app:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #  args:
    #    JAR_FILE: HouseManagement-1.0.0-SNAPSHOT.jar
    image: guestas/housemanagement:latest
    container_name: house_management_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATABASE:-house_app}
      SPRING_DATASOURCE_USERNAME: ${USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD:-postgres}

volumes:
  postgres_data: