version: '3.8'
services:
  db:
    image: postgres:14.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE:-house}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
