name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_with_docker_file_and_push_Docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get current version
        id: get_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [ -z "$version" ]; then
            echo "Version not found!"
            exit 1
          fi
          echo "Current version is $version"
          echo "::set-output name=current_version::$version"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug - Echo version
        run: |
         echo "Version is ${{ steps.get_version.outputs.current_version }}"
         echo "JAR file is ${{ env.jar_file }}"
        

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: JAR_FILE=${{ env.jar_file }}
          tags: |
            guestas/housemanagement:${{ steps.get_version.outputs.current_version }}
            guestas/housemanagement:latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/house_app
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: house_app
